spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: root1234
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

# Mybatis
mybatis:
  mapper-locations: classpath:/mappers/*.xml


logging:
  level:
    com.tripinfo: debug
