# Web ContextRootPath and PortNumber Settings
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
# JWT setting
jwt:
  salt: ssafy-screte-key
  #1 hour (millis)
  access-token :
    expiretime: 3600000
  # 30 days (millis)
  refresh-token:
    expiretime: 2592000000

# Mybatis
mybatis:
  mapper-locations: classpath:/mappers/*.xml


logging:
  level:
    com.tripinfo: debug
    


